
PDLIBBUILDER_DIR=${CURDIR}/deps/pd-lib-builder
HIDMAP_DIR=${CURDIR}/deps/USB-HID-Report-Parser

cflags +=  -I${HIDMAP_DIR}
ldflags += -lusb-1.0 -lhidapi

export PDLIBBUILDER_DIR
export HIDMAP_DIR
export cflags
export ldflags


all:
	$(MAKE) -C src/hid

install:
	$(MAKE) -C src/hid install

clean:
	$(MAKE) -C src/hid clean
